/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-request-settings-panel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {ArcSettingsPanelMixin} from '@advanced-rest-client/arc-settings-panel-mixin/arc-settings-panel-mixin.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

declare namespace UiElements {

  /**
   * Request settings panel for Advanced REST Client
   *
   * ## Styling
   *
   * `<arc-request-settings-panel>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-request-settings-panel` | Mixin applied to this elment | `{}`
   * `--arc-settings-panel-header` | Mixin applied to settings panel header | `{}`
   * `--arc-settings-panel-header-color` | Color of the settings panel header | `--accent-color`
   * `--arc-settings-panel-icon-color` | Settings panel icon color | `rgba(0, 0, 0, 0.34)`
   * `--arc-settings-panel-description` | Mixin applied to the description elements | `{}`
   * `--arc-settings-panel-description-color` | Description color  | `rgba(0,0,0,0.74)`
   * `--arc-font-body1` | Mixin apllied to the description elements | `{}`
   * `--arc-font-subhead` | Mixin applied to the section headers | `{}`
   */
  class ArcRequestSettingsPanel extends
    ArcSettingsPanelMixin(
    Object) {

    /**
     * Variables support enabled setting.
     */
    appVariablesEnabled: boolean|null|undefined;

    /**
     * Sequest default timeout setting.
     */
    requestDefaultTimeout: number|null|undefined;

    /**
     * Global option to follow redirects
     */
    followRedirects: boolean|null|undefined;

    /**
     * Collects information abour system variables when evaluating
     * request.
     */
    systemVariablesEnabled: boolean|null|undefined;

    /**
     * When set `systemVariablesEnabled` options is disabled.
     * Chrome apps does not have this option.
     */
    systemVariablesDisabled: boolean|null|undefined;

    /**
     * Default OAuth 2 redirect URI.
     */
    oauth2redirectUri: object|null;

    /**
     * The default value for the OAuth2 redirect URI if missing.
     */
    defaultOauth2RedirectUri: string|null|undefined;
    connectedCallback(): void;
    _processValues(values: any): any;
    _setSettings(values: any): void;
    _computeTimeoutLabel(requestDefaultTimeout: any): any;
    _varsChanged(value: any): void;
    _timeoutChanged(value: any): void;
    _redirectsChanged(value: any): void;
    _sysVarsChanged(value: any): void;
    _oauth2RedirectChanged(value: any): void;
    _settingsChanged(key: any, value: any): void;

    /**
     * Handles `change` event on OAuth2 redirect URI input.
     * Updates the value of corresponding `oauth2redirectUri` property.
     */
    _updateOAuthRedirect(e: Event|null): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "arc-request-settings-panel": UiElements.ArcRequestSettingsPanel;
  }
}
